-- 2.1
SELECT DISTINCT Fname
FROM EMPLOYEE JOIN DEPARTMENT ON Dno = Dnumber
WHERE Dname = 'Research';

-- 2.2
SELECT DISTINCT EMP.Fname
FROM EMPLOYEE MGR JOIN DEPARTMENT ON MGR.Ssn = Mgr_ssn
JOIN EMPLOYEE EMP ON MGR.Ssn = EMP.Super_ssn
WHERE Dname = 'Research';

-- 2.3
SELECT DISTINCT Fname
FROM EMPLOYEE JOIN DEPARTMENT ON Ssn = Mgr_ssn
WHERE Ssn NOT IN (SELECT Essn FROM WORKS_ON);

-- 2.4
SELECT Pname, SUM(Hours) AS Total_hours
FROM PROJECT JOIN WORKS_ON ON Pnumber = Pno
GROUP BY Pname;

-- 2.5
SELECT DISTINCT Fname
FROM EMPLOYEE JOIN WORKS_ON ON Ssn = Essn
WHERE Ssn NOT IN (
  SELECT Essn
  FROM PROJECT JOIN WORKS_ON ON Pnumber = Pno
  WHERE Plocation = 'Houston'
);

-- 2.6
SELECT DISTINCT Fname
FROM EMPLOYEE JOIN WORKS_ON WORKS_ON_OUT ON Ssn = Essn
WHERE NOT EXISTS (
  SELECT Pnumber
  FROM PROJECT LEFT JOIN (SELECT * FROM WORKS_ON WORKS_ON_IN WHERE WORKS_ON_OUT.Essn = WORKS_ON_IN.Essn) AS EMP_PRJ
  ON Pnumber = EMP_PRJ.Pno
  WHERE Plocation = 'Houston' AND EMP_PRJ.Pno IS NULL
);

-- 2.7
SELECT Fname, Salary
FROM EMPLOYEE
WHERE (Dno, Salary) IN (
  SELECT Dno, Max(Salary)
  FROM EMPLOYEE
  GROUP BY Dno
);

-- 2.8
SELECT Dname
FROM EMPLOYEE JOIN DEPARTMENT ON Dno = Dnumber
GROUP BY Dname
HAVING COUNT(*) >= 3;

-- 2.9
SELECT SUPERVISEE.Fname, SUPERVISEE.Bdate, SUPERVISOR.Fname, SUPERVISOR.Bdate
FROM EMPLOYEE SUPERVISEE JOIN EMPLOYEE SUPERVISOR ON SUPERVISEE.Super_ssn = SUPERVISOR.Ssn
WHERE SUPERVISEE.Bdate <= SUPERVISOR.Bdate;
